# Automatically increase all version numbers after the first field
name: 0.$(Year:yy).$(DayOfYear).$(Rev:r)

trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- job: Package
  displayName: Pre-test and package

  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.7
    displayName: 'Use Python 3.7'

  - script: python -m reportabug
    env:
      PYTHONPATH: src
    displayName: 'Basic test'

  - script: pip install pytest-azurepipelines && pytest --test-run-title="Pre-tests"
    displayName: 'Run unit tests against source'

  - script: python setup.py sdist -d $(build.ArtifactStagingDirectory)
    displayName: 'Build sdist'

  - script: pip wheel reportabug --find-links $(build.ArtifactStagingDirectory) -w $(build.ArtifactStagingDirectory)
    displayName: 'Build wheel'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: dist
      targetPath: $(build.ArtifactStagingDirectory)
    displayName: 'Publish dist to pipeline'

- template: azure-pipelines-test.yml
  parameters:
    vmImage: ubuntu-16.04
    name: Ubuntu

- template: azure-pipelines-test.yml
  parameters:
    vmImage: macOS-10.13
    name: macOS

- template: azure-pipelines-test.yml
  parameters:
    vmImage: vs2017-win2016
    python.architecture: x64
    name: Win64

- job: Publish
  displayName: Publish to Azure Artifacts

  dependsOn:
  - Ubuntu
  - macOS
  - Win64

  pool:
    vmImage: vs2017-win2016

  steps:
  - checkout: none

  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.7
    displayName: 'Use Python 3.7'

  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: dist
      targetPath: $(Build.BinariesDirectory)/dist
    displayName: "Download built package"

  - script: pip install twine
    displayName: 'Install Twine'

  - task: TwineAuthenticate@0
    inputs:
      artifactFeeds: ReportABug
    displayName: 'Configure Twine authentication'

  - script: twine upload -r ReportABug --config-file $(PYPIRC_PATH) "$(Build.BinariesDirectory)/dist/*"
    displayName: 'Upload to Artifacts'
